name: Copilot PR Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request Copilot review
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            // Request Copilot review (replace 'github-copilot[bot]' with your Copilot bot username if needed)
            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number,
              reviewers: ['github-copilot[bot]']
            });

  block-merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Block merge if Copilot comments unresolved
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            // Get all review comments
            const comments = await github.rest.pulls.listReviewComments({
              owner,
              repo,
              pull_number
            });
            // Filter for Copilot comments
            const copilotComments = comments.data.filter(
              c => c.user && c.user.login === 'github-copilot[bot]' && !c.resolved
            );
            if (copilotComments.length > 0) {
              throw new Error(`PR cannot be merged: ${copilotComments.length} Copilot comments unresolved.`);
            }
